# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqEQY0OxT8mnP7-_snzqEeWsxVo2Ib5n
"""

def is_ood(x):
    if x %2 == 1:
        return True
    else:
        return False

print(is_odd(33))
print(is_odd(546))