# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZQvxlPeLL-tr0LRX_Xr5x-sHdsHC2iv
"""

def absolute_value(x,y)
  if (x<y):
     return 1
  else if (x=y):
     return 0
  else if (x>y):
     return -1